### PR TITLE
Updated the access token generation workflow

### PR DESCRIPTION
**Pull request by ashiqueps**
### Description

On https://github.com/test-kitchen/vmware-vra-gem/pull/85, the workflow for the access token generation was updated. Since some of the test cases were failing on the PR, I've pulled the changes added by @chef-davin and updated the specs here.

### Issues Resolved
Resolves issue discovered by user in working session with Chef CA

### Check List

- [x] All tests pass.
- [x] All style checks pass.
- [x] Functionality includes testing.
- [x] Functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by ashiqueps** [comment]
Hey @damacus / @Xorima,

Could you please review this PR?

cc: @tas50

**Review by Xorima — APPROVED** [review]

**Comment by tas50** [comment]
Thanks @chef-davin and @ashiqueps

**Comment by vkarve-chef** [comment]
could someone please merge this PR?

**Comment by tas50** [comment]
@vkarve-chef this shipped as 3.0.1

**Pull request merged**
