### PR TITLE
Use regular vs admin catalog endpoint to fetch catalog items

### LINKED ISSUE #93: Catalog API endpoint needlessly requires full admin privileges
## :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

The APIs to get entitled catalog items hits the admin endpoint URL rather than the usual endpoint URL, in essence requiring full administrator privilege in VRA. 

## Version

v3.1.1

## Environment

Any OS, v3.1.1 gem used against vRA 8

## Scenario

Use VRA::Catalog to try to either get all entitled catalog items, or an entitled item, as a user with some, but not full admin, privileges.  Instead of getting the catalog items this user id is entitled for, the gem returns permission denied error.

## Steps to Reproduce

🦖 Call one of these methods: `client.catalog.all_items`, `client.catalog.entitled_items(project)`, or `client.catalog.fetch_catalog_items(by_name)`

## Expected Result

🆗 Should have gotten details about the catalog item(s) requested if this user id is entitled to them.

## Actual Result

⛔ Get permission denied even if the user id has access to that catalog.

## :heavy_plus_sign: Additional context

I'll send you a PR for this shortly.

### PR DESCRIPTION
**Pull request by oshvarts**
### Description

It uses regular /api/items catalog endpoint rather than the /api/admin/items endpoint to avoid requirement of using this gem as full VRA admin.  Using regular endpoint, user can operate with their entitled catalog items.

### Issues Resolved

Closes #93 

### Check List

- [x] All tests pass.
- [x] All style checks pass.
- [x] Functionality includes testing.
- [ ] Functionality has been documented in the README if applicable (N/A as behind the scenes change)

### CODE REVIEW

**Comment by oshvarts** [comment]
Admins, the unit tests succeeded but linters seem to hang.  could you please check the github actions setup?

**Review by ashiqueps — DISMISSED** [review]

**Review by vkarve-chef — APPROVED** [review]

**Comment by vkarve-chef** [comment]
@damacus is there a way to overcome the hung checks? i believe admins should have a way to force merge?

**Comment by damacus** [comment]
@kasif-adnan can you copy the reusable workflow from one of the other repos, please? 

That should fix this error

**Comment by kasif-adnan** [comment]
> @kasif-adnan can you copy the reusable workflow from one of the other repos, please?
> 
> That should fix this error
@damacus , i have a separate PR open for that https://github.com/test-kitchen/vmware-vra-gem/pull/97 . probably we could merge that prior to this

**Comment by kasif-adnan** [comment]
> @kasif-adnan can you copy the reusable workflow from one of the other repos, please?
> 
> That should fix this error
@damacus , i have a separate PR open for that https://github.com/test-kitchen/vmware-vra-gem/pull/97 . probably we could merge that prior to this

**Comment by kasif-adnan** [comment]
@oshvarts , could you please pull in the latest changes from main ? It should then be ready to merge

**Comment by oshvarts** [comment]
@kasif-adnan  updated, thank you, please re-review.

**Comment by kasif-adnan** [comment]
> @kasif-adnan updated, thank you, please re-review.

Changes not related to this PR have come in. Maybe a rebase could clean it up

**Comment by oshvarts** [comment]
> Changes not related to this PR have come in. Maybe a rebase could clean it up

This _was_ a rebase -- as the style changes conflicted on the same lines as my changes.   Please take a look again - but if it's not acceptable, let me know, I can drop this Pr and redo it from scratch.  As long as no one frontruns me.

**Comment by kasif-adnan** [comment]
> > Changes not related to this PR have come in. Maybe a rebase could clean it up
> 
> This _was_ a rebase -- as the style changes conflicted on the same lines as my changes. Please take a look again - but if it's not acceptable, let me know, I can drop this Pr and redo it from scratch. As long as no one frontruns me.

it would be great if you could just drop this PR and open a new one. would be easier to review and merge it. Thanks!

**Comment by oshvarts** [comment]
@kasif-adnan ,  sure, I'll do that.

Could you please merge #98 first so I'd have a stable `main` to start from?  Otherwise we'll have another preemption issue. thanks.

**Pull request closed without merging**
